### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ronitx05** [Khanejo/Instagram-mass-reporter#43]
FileNotFoundError: [Errno 2] No such file or directory: 'acc.txt'

**Comment by ghost** [comment]
Hi, create file named **acc.txt** into the folder.
Open it and add your account username and password like this **username:password**, then save. #44 
I hope have helped you :)

**Comment by ARRARIAKU2** [comment]
> I hope have helped you :)

i got this :(

Traceback (most recent call last):
  File "InstagramReportBot2.py", line 43, in <module>
    web = Browser()
  File "D:\anaconda3\envs\flask\lib\site-packages\webbot\webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
  File "D:\anaconda3\envs\flask\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__ 
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "D:\anaconda3\envs\flask\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "D:\anaconda3\envs\flask\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__

    self.start_session(capabilities, browser_profile)
  File "D:\anaconda3\envs\flask\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\anaconda3\envs\flask\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute 
    self.error_handler.check_response(response)
  File "D:\anaconda3\envs\flask\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception: Missing or invalid capabilities
  (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 10.0.22000 x86_64)

**Comment by LaxmanChoudhary** [comment]
okay right got it

**Comment by thunder0411** [comment]
> okay right got it

yeah i am also getting same error . do you have any solution ?
