### ISSUE TITLE
Getting these error what to do??

### ISSUE THREAD

**Issue by Krajveer** [Khanejo/Instagram-mass-reporter#52]
Traceback (most recent call last):
  File "/workspaces/Instagram-mass-reporter/Instagram Report Bot2.py", line 45, in <module>
    web = Browser()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/webbot/webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception: Missing or invalid capabilities
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 5.4.0-1106-azure x86_64)

**Comment by Krajveer** [comment]
Chrome is up to date

**Comment by Tecspay** [comment]
I have the same problem I don't know what to do !
